### ISSUE TITLE
gutter icons with diffs from another branches are not displayed after upgraded from 17.1.2

### ISSUE THREAD

**Issue by alesak** [GitLiveApp/GitLive#160] opened 2024-08-20 17:35 UTC
After upgraded from 17.1.2 gutter icons showing differences from other branches are no longer displayed, currently on 18.0.0-eap3

**Comment by nbransby** [comment] 2024-08-23 05:29
Thanks @alesak , fix planned for eap4

**Comment by nbransby** [comment] 2024-09-04 14:48
@alesak eap4 is now avaialble

**Comment by alesak** [comment] 2024-09-05 13:17
eap4 installed but still no gutter icons and the GitLive context menu in gutter right click is disabled

**Comment by nbransby** [comment] 2024-09-05 14:02
@alesak do you have an example git repo you can share that you can reproduce the issue with?

**Comment by alesak** [comment] 2024-09-05 14:33
It is simple GitoLite setup, I don't have any public repository but I can create one private for your testing, I will need your RSA public key... I just did few tests, when the remote is defined as **git@git.???.com.au:repo-name** the menu is disabled, when I change it to **ssh://git@git.????.com.au/repo-name.git** the menu is active but all options are disabled and the gutter icons are not present in both cases. When the repository is hosted on GitHub or GitLab everything seams to work

**Comment by alesak** [comment] 2024-09-05 14:44
I believe GitoLite repositories are basically same as normal GIT server (https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server) no repository hosted this way is displaying the gutter icons

**Comment by nbransby** [comment] 2024-09-06 03:20
Thanks for the information, we'll try and reproduce the issue our end

**Comment by nbransby** [comment] 2024-09-07 06:26
Our testing reveals the gutter is not shown for branches from a gitolite remote only when they are mulitple remotes in the repository, could you confirm that is the same behavior you are seeing?

**Comment by alesak** [comment] 2024-09-07 13:37
hard to say,  I usually have multiple remotes but eap4 seams to have another problem and is crashing (seams more often once I removed off the remote):

2024-09-07 23:23:06,200 [  25608] SEVERE - GitLive - a@1lkep38:p@megbip java.util.NoSuchElementException: Array contains no element matching the predicate.
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at dev.gitlive.internal.d.a.E.invoke(SourceFile:1336)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at dev.gitlive.internal.d.a.aV.emit(SourceFile:223)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-09-07 23:23:06,206 [  25614] SEVERE - GitLive - IntelliJ IDEA 2024.2.1  Build #IU-242.21829.142

**Comment by alesak** [comment] 2024-09-07 13:45
I believe you are correct when I open the IDE without any file previously opened GitLive did not immediately crashed and it displays the gutter info but without the photo of whoever made the change which was very handy in previous version...

**Comment by nbransby** [comment] 2024-09-07 15:57
Ok so both the crash and the missing gutter info should be fixed in the next version but the photos can only show for commits from a branch on a remote from GitHub, GitLab, Bitbucket or Azure or if the commit author's email address has a gravatar.

**Comment by alesak** [comment] 2024-09-07 23:38
Will test it as soon as the new version is available, those icons were very useful any chance to have them back? It was working well in 17.1.2 even for GitoLite and all our developers have a gravatar...

**Comment by nbransby** [comment] 2024-09-08 00:02
What do you see instead of their gravatar?

**Comment by alesak** [comment] 2024-09-08 00:18
![2024-09-08_10-17](https://github.com/user-attachments/assets/d30fdafc-094c-4220-b99b-3c1f94237241)

**Comment by nbransby** [comment] 2024-09-08 00:27
This implies the change is in a special branch, you can read more about that here: https://blog.git.live/GitLive-16.1-get-notified-when-you-fall-behind-the-remote-and-more-new-features#specify-which-branches-are-not-feature-branches

If you modify the regex from the default (below)to not match the branches you want to want to see avatars for they should return:
`main|master|trunk|dev|develop|qa|test|release[-/].*`

**Comment by alesak** [comment] 2024-09-08 00:54
Unable to confirm, it is crashing too often but same branches are there for years and I never changed the default empty value for feature branches so something has changed..., have to catch the plane will be available for testing in 36 hours

**Comment by nbransby** [comment] 2024-09-08 02:01
In that case I suspect it's due to the limit of the free plan (only shows the 10 most recent branches), this was previously only enforced in the repository tree view and not the gutter indicators. 

Have you signed up for a paid plan?

**Comment by alesak** [comment] 2024-09-16 11:46
I would sign up if I can find a way to get the license

**Comment by alesak** [comment] 2024-09-16 12:00
anyway, I can't see faces in any branch in any project in any repository so I suspect the problem is elsewhere

**Comment by nbransby** [comment] 2024-09-19 12:47
Please try again with the latest eap which should be released before the end of the week

**Comment by alesak** [comment] 2024-09-20 17:55
I can see some gravatar icons so it seams to be working just they are so small, it is very hard to see what is on them...
![Screenshot_20240920_195346](https://github.com/user-attachments/assets/f06c6cc5-afe5-4fca-a650-505103c38ff9)

**Comment by nbransby** [comment] 2024-09-22 14:42
looks like the gravatar is not square so you get a letterbox effect

**Closed as completed by nbransby** 2024-09-22 14:42 UTC
