### ISSUE TITLE
Can't work on issues with long names, silent exception

### ISSUE THREAD

**Issue by amogorkon** [GitLiveApp/GitLive#85] opened 2021-09-22 09:55 UTC
I really like the feature of gitlive that encourages feature-branches with the `#-name` schema and asks the user to pick an issue, which is a great workflow. However, it confused me a great deal when I tried to pick an issue that had slightly longer name than usual (`It should be possible to use a package via "package:module", ("package", "module") or kwarg package="package", module="module"`). I expected that gitlive would trunkate or at least display an error message, but instead it simply wouldn't comply with me selecting the issue. It worked once I shortened the name.
This is a big no-no in UX-design, please fix.

**Comment by Reedyuk** [comment] 2021-09-22 09:58
Hi @amogorkon - thanks for the feedback.
Can you show me a screenshot of what you mean? Are you saying you see the issue but when you click it, it doesn't do anything? 
We actually do truncate the length, but maybe we need to adjust this more.

**Comment by Reedyuk** [comment] 2021-09-27 15:57
@amogorkon - i have investigated your issue and was unable to reproduce the issue.

Maybe you could give me some more information on the issue? Can you make sure you have the latest plugin and try again.

<img width="837" alt="Screenshot 2021-09-27 at 16 55 16" src="https://user-images.githubusercontent.com/3853006/134943125-8815e486-ed0e-41a7-b558-1c56db1a5d9c.png">
<img width="1341" alt="Screenshot 2021-09-27 at 16 55 09" src="https://user-images.githubusercontent.com/3853006/134943129-d88b1803-74ff-4995-ae42-49b18fca3e4a.png">
<img width="1276" alt="Screenshot 2021-09-27 at 16 55 00" src="https://user-images.githubusercontent.com/3853006/134943134-ab536672-149a-4fe3-9562-156824e673d7.png">

**Comment by amogorkon** [comment] 2021-09-28 16:28
Strange.. I'll try again and see if I can reproduce with a new, very long issue.

**Comment by amogorkon** [comment] 2021-09-28 16:43
OK, now. The github issue title limit is 256, so I made an issue with exactly that length: https://github.com/amogorkon/justuse/issues/281
It seems to work now, but two other, small issues I noticed with the indicators: the underscores in the title are missing, which probably should be handled like whitespace and just be replaced with single-underscores and no indication of truncation in the status bar.
![Unbenannt](https://user-images.githubusercontent.com/16521496/135129266-331b90e9-7a1c-4321-93ec-3269f20fb4ed.PNG)

**Comment by amogorkon** [comment] 2021-09-28 16:46
I'll try to replicate the original issue to rule out special character issues..

**Comment by amogorkon** [comment] 2021-09-28 16:51
I just noticed that the status bar button is missing where i can select a new issue :-s

**Comment by amogorkon** [comment] 2021-09-28 16:55
Alright, I made a new issue: https://github.com/amogorkon/justuse/issues/282
This time, it looks like it's working as it should, also no missing status bar button (even though it's very large and should probably be truncated a few characters past the number like `#282 gitlive test[...]`
![Unbenannt](https://user-images.githubusercontent.com/16521496/135131425-c0676101-8027-4740-8eaa-a195bce97faa.PNG)

**Comment by Reedyuk** [comment] 2021-09-28 16:57
strange that it didn't work first time though, the only thing that i can think of, was you were using an older version of the extension(was several releases back) where i made the change to truncate the issue length.

**Comment by amogorkon** [comment] 2021-09-28 16:58
wait a second.. *all* special characters are missing from the title?
![Unbenannt](https://user-images.githubusercontent.com/16521496/135132012-86c0302a-dcc7-4cd7-9f31-304d782b7918.PNG)

**Comment by Reedyuk** [comment] 2021-09-28 16:58
Yes, that is required, otherwise it is not possible to create the git branch.

**Comment by amogorkon** [comment] 2021-09-28 17:02
My release now is v14.0.4, if that is of any use. Well, it seems to work now as it should, albeit with a few rough edges. Thanks for your time and keep up the good work :)

**Comment by Reedyuk** [comment] 2021-09-28 17:05
Thanks!
I'm glad its working now, please raise any other issues you may find. 
I will close this issue, but re-open it if you find a reproducible example.

**Closed by Reedyuk** 2021-09-28 17:05 UTC
