### ISSUE TITLE
Unresponsive service

### ISSUE THREAD

**Issue by FredCoen** [GitLiveApp/GitLive#31] opened 2021-02-03 12:01 UTC
When based in Europe service seems to lag due to network issues.

**Comment by criedel** [comment] 2021-02-04 22:17
we tried gitlive today again (because your competitor's product was broken). 
I was following my colleagues cursor. after a while he opened a file that wasnt in git yet and I couldnt see it. he switched back to a  file that was in source control and I could see the cursor again. next step was to commit the file so I can follow the changes, but that made everything worse and now gitlive wouldn't pick up any file in the repo that my colleague was working on. multiple connection restarts later we gave up.

**Comment by nbransby** [comment] 2021-02-06 22:40
Hi @criedel thanks for the report, sorry to hear you were having issues. 
Could you confirm what IDE and version of the plugin both you and your colleague were using? Also were you working on a repository from GitHub using this account (criedel) or a different one?

**Comment by criedel** [comment] 2021-02-07 10:49
Both using Rider 2020.3.2, working on a private repo from this account, yes.

**Comment by nbransby** [comment] 2021-02-07 19:38
Thanks, and when wouldn't pick up any file in the repo that your colleague was working on, do you mean it wasnt opening the same file in your IDE? We have found an issue with the follow cursor switching itself off (you need to manually switch it on again to catch up with your colleague's cursor) which will be fixed in the next version, maybe this was the cause of your issue?

Also I'm assuming you were both using the latest version of the plugin (10.0.5)

**Comment by criedel** [comment] 2021-02-08 11:41
he was working on a file and the follow cursor option has not been working. in fact, no changes on my colleague's side made it to my computer. toggling the follow cursor option did not fix it and neither did restarting the session.

**Comment by FredCoen** [comment] 2021-02-08 15:17
hi @criedel can you provide me with the github user name of your teammate you faced those issues with?

**Closed** 2021-10-10 18:53 UTC
